### ISSUE TITLE
Revocation List and Restful APIs

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-http-api#204] opened 2021-06-22 20:34 UTC
Revocation List VCs require an `id`.

All examples of revocaiton list vc todate, have followed a "collection" api format:

`id: https://example.com/credentials/123`

```
  "credentialStatus": {
    "id": "https://issuer.oidp.uscis.gov/credentials/status/3#94567",
    "type": "RevocationList2020Status",
    "revocationListIndex": "1",
    "revocationListCredential": "https://w3c-ccg.github.io/vc-http-api/fixtures/revocationList.json"
  },
  ```

**Comment by OR13** [comment] 2021-06-22 20:39
This can create awkwardness, when you want to support `POST /credentials` and `GET /credentials/:id` and `POST /credentials/issue`

**Comment by peacekeeper** [comment] 2021-06-22 21:21
Can you add a few more details what the issue is here?

In any case, this may be related to https://github.com/w3c-ccg/vc-http-api/issues/126 where I pointed out that the current `updateCredentialStatus` operation won't work for VCs that don't have an `id` (which is optional in VCs).

**Comment by msporny** [comment] 2021-07-10 13:51
At the very least, we need to determine how the client tells the issuer that they 1) manage the revocation list, or 2) use an external revocation list.

My suggestion would be that just specifying the following when issuing as an issuing option tells the issuer software that you want the issuer software to manage the revocation list:

```
issue.options:
  "credentialStatus": {
    "type": "RevocationList2021"
  }
```

Not specifying that, but doing something like this in the VC tells the issuer that revocation will be handled by an external system:

```
issue.credential:
  "credentialStatus": {
    "id": "https://dmv.example.gov/credentials/status/3#94567",
    "type": "RevocationList2021Status",
    "statusListIndex": "94567",
    "statusListCredential": "https://example.com/credentials/status/3"
  }
```

**Comment by OR13** [comment] 2021-07-13 20:15
I am in favor of doing this, after documenting current behavior.

**Comment by OR13** [comment] 2021-07-13 20:18
@peacekeeper can you propose specific changes you would like to see to how revocation is documented and tested?

**Comment by peacekeeper** [comment] 2021-07-13 20:20
@OR13 I simply don't understand what this issue is about. It starts with saying something about `id` and showing an example, and then there is some proposal by @msporny. But there is no explanation anywhere what is the exact issue, or what is being solved with the proposal, or how.

If possible, can you add a better explanation of what this issue is all about?

**Comment by OR13** [comment] 2021-07-13 20:21
@peacekeeper The issue is that revocation is not documented or tested sufficiently, the solution is to improve documentation by updating JSON Schema, and possibly by adding informative text to respec.

**Comment by peacekeeper** [comment] 2021-07-13 20:39
> @peacekeeper The issue is that revocation is not documented or tested sufficiently / at all, the solution is to improve documentation by updating JSON Schema, and possibly by adding informative text to respec.

Sounds good, I agree with that. Can we then close this issue and open another one which just says that?

**Comment by OR13** [comment] 2021-07-13 20:41
I'm fine with you doing that :)

**Comment by msporny** [comment] 2021-09-06 15:34
@OR13 assigning to you so we can close this issue.

**Closed** 2021-09-13 18:35 UTC
